name: Deploy Frontend to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ahmedadelabdelmohsen/rowling-gradproject-frontend:latest .
          docker push ahmedadelabdelmohsen/rowling-gradproject-frontend:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete existing Azure Container Instance
        run: az container delete --resource-group rowling-gradproject --name rowling-frontend-container --yes

      - name: Create new Azure Container Instance
        run: |
          az container create --resource-group rowling-gradproject --name rowling-frontend-container --image ahmedadelabdelmohsen/rowling-gradproject-frontend:latest --dns-name-label rowling-frontend --ports 80 --environment-variables PORT=80 --registry-login-server index.docker.io --registry-username ahmedadelabdelmohsen --registry-password ${{ secrets.DOCKER_PASSWORD }}
